export const PERMISSIONS = {
  // Organization
  ORGANIZATION: {
    READ: 'ORGANIZATION.READ',
    UPDATE: 'ORGANIZATION.UPDATE',
    DELETE: 'ORGANIZATION.DELETE',
    MANAGE_SUBSCRIPTION: 'ORGANIZATION.MANAGE_SUBSCRIPTION',
    SUSPEND: 'ORGANIZATION.SUSPEND',
    ACTIVATE: 'ORGANIZATION.ACTIVATE',
  },

  // User
  USER: {
    READ: 'USER.READ',
    CREATE: 'USER.CREATE',
    UPDATE: 'USER.UPDATE',
    DELETE: 'USER.DELETE',
    MANAGE: 'USER.MANAGE',
  },

  // Role
  ROLE: {
    READ: 'ROLE.READ',
    CREATE: 'ROLE.CREATE',
    UPDATE: 'ROLE.UPDATE',
    DELETE: 'ROLE.DELETE',
    ASSIGN: 'ROLE.ASSIGN',
  },

  // Hotel
  HOTEL: {
    READ: 'HOTEL.READ',
    CREATE: 'HOTEL.CREATE',
    UPDATE: 'HOTEL.UPDATE',
    DELETE: 'HOTEL.DELETE',
    MANAGE: 'HOTEL.MANAGE',
  },

  // Room
  ROOM: {
    READ: 'ROOM.READ',
    CREATE: 'ROOM.CREATE',
    UPDATE: 'ROOM.UPDATE',
    DELETE: 'ROOM.DELETE',
    MANAGE: 'ROOM.MANAGE',
  },

  // Reservation
  RESERVATION: {
    READ: 'RESERVATION.READ',
    CREATE: 'RESERVATION.CREATE',
    UPDATE: 'RESERVATION.UPDATE',
    DELETE: 'RESERVATION.DELETE',
    CHECK_IN: 'RESERVATION.CHECK_IN',
    CHECK_OUT: 'RESERVATION.CHECK_OUT',
  },

  // Admin
  ADMIN: 'ADMIN',
  SUPER_ADMIN: 'SUPER_ADMIN',
} as const;

// Helper type
export type Permission =
  | (typeof PERMISSIONS)[keyof typeof PERMISSIONS]
  | (typeof PERMISSIONS.ORGANIZATION)[keyof typeof PERMISSIONS.ORGANIZATION]
  | (typeof PERMISSIONS.USER)[keyof typeof PERMISSIONS.USER];
