export const PERMISSIONS = {
  // Organization
  ORGANIZATION: {
    CREATE: 'ORGANIZATION.CREATE',
    READ: 'ORGANIZATION.READ',
    UPDATE: 'ORGANIZATION.UPDATE',
    DELETE: 'ORGANIZATION.DELETE',
    MANAGE_SUBSCRIPTION: 'ORGANIZATION.MANAGE_SUBSCRIPTION',
    SUSPEND: 'ORGANIZATION.SUSPEND',
    ACTIVATE: 'ORGANIZATION.ACTIVATE',
  },

  // User
  USER: {
    READ: 'USER.READ',
    CREATE: 'USER.CREATE',
    UPDATE: 'USER.UPDATE',
    DELETE: 'USER.DELETE',
    MANAGE: 'USER.MANAGE',
  },

  // Role
  ROLE: {
    READ: 'ROLE.READ',
    CREATE: 'ROLE.CREATE',
    UPDATE: 'ROLE.UPDATE',
    DELETE: 'ROLE.DELETE',
    ASSIGN: 'ROLE.ASSIGN',
  },

  // Hotel
  HOTEL: {
    READ: 'HOTEL.READ',
    CREATE: 'HOTEL.CREATE',
    UPDATE: 'HOTEL.UPDATE',
    DELETE: 'HOTEL.DELETE',
    MANAGE: 'HOTEL.MANAGE',
  },

  // Room
  ROOM: {
    READ: 'ROOM.READ',
    CREATE: 'ROOM.CREATE',
    UPDATE: 'ROOM.UPDATE',
    DELETE: 'ROOM.DELETE',
    ASSIGN: 'ROOM.ASSIGN',
    UPGRADE: 'ROOM.UPGRADE',
    CHANGE: 'ROOM.CHANGE',
    BULK_UPDATE: 'ROOM.BULK_UPDATE',
    STATUS_UPDATE: 'ROOM.STATUS_UPDATE',
    OOO_MANAGE: 'ROOM.OOO_MANAGE',
    HISTORY_READ: 'ROOM.HISTORY_READ',
    MANAGE: 'ROOM.MANAGE',
  },

  // Reservation
  RESERVATION: {
    READ: 'RESERVATION.READ',
    CREATE: 'RESERVATION.CREATE',
    UPDATE: 'RESERVATION.UPDATE',
    DELETE: 'RESERVATION.DELETE',
    CANCEL: 'RESERVATION.CANCEL',
    CHECK_IN: 'RESERVATION.CHECK_IN',
    CHECK_OUT: 'RESERVATION.CHECK_OUT',
    ASSIGN_ROOM: 'RESERVATION.ASSIGN_ROOM',
    NO_SHOW: 'RESERVATION.NO_SHOW',
    SPLIT: 'RESERVATION.SPLIT',
  },

  // Check-in
  CHECKIN: {
    PERFORM: 'CHECKIN.PERFORM',
    EARLY: 'CHECKIN.EARLY',
    WALKIN: 'CHECKIN.WALKIN',
    OVERRIDE_BLACKLIST: 'CHECKIN.OVERRIDE_BLACKLIST',
    WAIVE_PREAUTH: 'CHECKIN.WAIVE_PREAUTH',
  },

  // Check-out
  CHECKOUT: {
    PERFORM: 'CHECKOUT.PERFORM',
    EXPRESS: 'CHECKOUT.EXPRESS',
    LATE: 'CHECKOUT.LATE',
    NO_SHOW: 'CHECKOUT.NO_SHOW',
    WAIVE_FEE: 'CHECKOUT.WAIVE_FEE',
    REINSTATE: 'CHECKOUT.REINSTATE',
  },

  // Front desk
  FRONTDESK: {
    DASHBOARD: 'FRONTDESK.DASHBOARD',
  },

  // Guest
  GUEST: {
    READ: 'GUEST.READ',
    CREATE: 'GUEST.CREATE',
    UPDATE: 'GUEST.UPDATE',
    DELETE: 'GUEST.DELETE',
    MERGE: 'GUEST.MERGE',
    UPDATE_VIP: 'GUEST.UPDATE_VIP',
  },

  // Housekeeping
  HOUSEKEEPING: {
    READ: 'HOUSEKEEPING.READ',
    CREATE: 'HOUSEKEEPING.CREATE',
    UPDATE: 'HOUSEKEEPING.UPDATE',
    ASSIGN: 'HOUSEKEEPING.ASSIGN',
    START_TASK: 'HOUSEKEEPING.START_TASK',
    COMPLETE_TASK: 'HOUSEKEEPING.COMPLETE_TASK',
    MARK_DND: 'HOUSEKEEPING.MARK_DND',
    CANCEL: 'HOUSEKEEPING.CANCEL',
    AUTO_GENERATE: 'HOUSEKEEPING.AUTO_GENERATE',
    INSPECT: 'HOUSEKEEPING.INSPECT',
    REPORT: 'HOUSEKEEPING.REPORT',
    SHIFT_MANAGE: 'HOUSEKEEPING.SHIFT_MANAGE',
    DASHBOARD_READ: 'HOUSEKEEPING.DASHBOARD_READ',
    LOST_FOUND_LOG: 'HOUSEKEEPING.LOST_FOUND_LOG',
    LOST_FOUND_UPDATE: 'HOUSEKEEPING.LOST_FOUND_UPDATE',
    LOST_FOUND_NOTIFY: 'HOUSEKEEPING.LOST_FOUND_NOTIFY',
  },

  // Admin
  ADMIN: 'ADMIN',
  SUPER_ADMIN: 'SUPER_ADMIN',
} as const;

// Helper type
type NestedValueOf<T> = T extends string ? T : { [K in keyof T]: NestedValueOf<T[K]> }[keyof T];

export type Permission = NestedValueOf<typeof PERMISSIONS>;
